{ config, pkgs, host, lib, inputs, userconf, ... }:

{
  ################################################################
  # Module Imports
  ################################################################
  imports = [
    # Host-specific hardware (autogenerated)
    ./hardware-configuration.nix

    # Nyx-Modules  
    inputs.nyx-modules.nixosModules.default

    # Hardware-specific modules
    inputs.nyx-modules.nixosModules.hardware
 ];


  ################################################################
  # Nyx Modules
  ################################################################
  nyx-module = {
    ################################################################
    # Hardware Specific Configuration
    ################################################################
    hardware = {
      bluetooth.enable = true;
      # this is exclusively for certain Microsoft Surface:
      Custom-Kernel.SurfacePro-KabyLake = {
        enable        = false;
      };
    };
    system = {
      ################################################################
      # SSH Configuration
      ################################################################
      openssh = {
        enable         = true;
        passwordAuth   = false;
        permitRootLogin = "no";
      };

      ################################################################
      # Containerization & Virtualization
      ################################################################
      podman.enable = false;
      docker.enable = false;
      vm.enable     = false;

      ################################################################
      # Flatpak
      ################################################################
      flatpak.enable = false;

      ################################################################
      # Shell / Zsh Configuration
      ################################################################
      zsh = {
        enable   = true;
        ohMyZsh  = true;
        theme    = "xiong-chiamiov-plus";
        plugins  = [ "git" ];
      };

      ################################################################
      # Gaming
      ################################################################
      steam = {
        enable       = true;
        openFirewall = {
          remotePlay                = true;
          dedicatedServer           = true;
          localNetworkGameTransfers = true;
        };
      };

      ################################################################
      # Network Tools
      ################################################################
      wireshark = {
        enable   = false;
        username = username;
      };

      ################################################################
      # Developer Tools / Compilers
      ################################################################
      c-compiler.enable = true;
      go.enable         = true;
      lua.enable        = true;
      python.enable     = true;
      rust.enable       = true;

    };
  };



  ################################################################
  # Home Manager Configuration
  ################################################################

  home-manager = {
    # your Homemanager config
  };


  ################################################################
  # System Version
  ################################################################

  system.stateVersion = # your system Version;
}
